theme = "lynx"
title = "Fabian Gebhart"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Fabian Gebhart"
  # headline = "Data Engineer, Python Enthusiast, 3D-Printing Geek, Map Lover and Mountainbike Daredevil."
  image = "fgebhart.jpg"
  links = [
    { font-awesome = { href = "https://blog.fgebhart.dev", text = "&nbsp My Blog" } },
    { mastodon = { href = "https://fosstodon.org/@fgebhart", text = "&nbsp Mastodon"} },
    { github = { href = "https://github.com/fgebhart", text = "&nbsp Github"} },
    { reddit = { href = "https://www.printables.com/social/201896-fgebhart/models", text = "&nbsp Printables", icon = "link" } },
    { linkedin = { href = "https://www.linkedin.com/in/fabian-gebhart", text = "&nbsp LinkedIn"} },
    # { medium = { href = "https://3dmaps.fgebhart.dev/", text = "&nbsp My Shop", icon = "link" } },
    { twitter = { href = "https://twitter.com/FabianGebhart", text = "&nbsp Twitter"} },
    { reddit = { href = "https://www.strava.com/athletes/116825435", text = "&nbsp Strava", icon = "link" } },
    # { link = { href = "styles/", text = "All the link styles", target = "_self" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
